name: Nextjs CI

on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.IP }} << EOF
            cd /var/www/fit-flow/dev/client/ff-frontend
            git pull
            nvm use 16.15.1
            npm install
            npm run build
            pm2 stop dev-ff-frontend
            pm2 stop dev-ff-frontend
          EOF
